### ISSUE TITLE
submitter ip address in database

### ISSUE THREAD

**Issue by robot-o** [Corridors-of-Time-Transcription/puzzlepieces#11]
potential privacy issues when storing that in database (GDPR)
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/a593b65456de19cc6aa00ec08e4f8ea560f36e5f/src/collector/models.py#L7

https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/a593b65456de19cc6aa00ec08e4f8ea560f36e5f/src/collector/models.py#L29

**Comment by thorsteneb** [comment]
Yes, it is. Changed the code to store a hash of the IP instead.
