### ISSUE TITLE
Support for letter notation in addition to Raw JSON

### ISSUE THREAD

**Issue by ebuch** [Corridors-of-Time-Transcription/puzzlepieces#20]
We should add support for the community-standardized letter notation for images. Ideally it would be entered into the same text box as the Raw JSON.

This would be useful for people who might dislike using the tjl.co website or are used to transcribing this way. It would also be a great way to remain self-sufficient in the event the tjl.co website goes offline again.

**Comment by ebuch** [comment]
This would be a great feature to add prior to opening the floodgates, as many transcribers from stream teams would probably prefer to not change transcription methods. Is anybody free to work on this ASAP?

**Comment by afriestad** [comment]
I am free to do so.

**Comment by afriestad** [comment]
String should be of the form `B 1,2,3,4,5,6 BBBBBBB BBBBBBB BBBBBBB BBBBBBB BBBBBBB BBBBBBB`, correct?

**Comment by ebuch** [comment]
Yes, however—the stream spreadsheets have been notating the Openings of the puzzle piece, and I think our database is still storing the Walls of the puzzle piece (unless somebody has inverted that data). Can you check our data base and see?

**Comment by philiptaylor** [comment]
On https://tjl.co/corridors-of-time/ the table output shows openings, and the JSON output uses walls.

Our database stores walls. Our CSV export was buggy (sorry) and reported walls in a column labeled "Openings". Once #45 is deployed, the CSV export should report openings in the column labeled "Openings".

If you're manually typing in data, I suspect it'd be least confusing to match the table output and most people's spreadsheets, i.e. list openings from 1-6. Then the server will need to translate it to walls for the database.

**Comment by afriestad** [comment]
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/a934bb89271c8a6b3ba8fde50fa7a642efcc93e7/src/collector/models.py#L41-L46

The data is still named walls, and the JSON from TJL gives walls. I am not sure whether the content has been inverted, but I hope not since it has not been renamed. It should be easy to invert that on the non-JSON input.

**Comment by afriestad** [comment]
I looked through https://docs.google.com/spreadsheets/d/1bYi_-XApwf_avyIuExGULdWa4oxzLr7upelAtRq38TA/edit#gid=710933392 for some example strings, and found the following:

`"Clover	3,6	SDBHDHD	PSHPPDS	DTPHCCD	TSCBBPP	TSBDTDC	BPTCDBS"`
`"Plus	1,2,3,5,6	SDHCPCD	HDPPCTC	CPDSPHT	TPSSTCP	CPHBSCD	HCPPDSB"`
`"Clover	1,3,5	CCSDDCP	BBTTDSH	STCSDSS	PTPPSDP	SPBSCBS	SCDCTTC"`
`"Plus	6	HDPDSDH	PDSSTBP	PBTTPCP	SCCBTBD	TPHDDPS	TSCDBHT"`

There are two caveats here that oppose my previous statement; the center symbol is fully written out, and the values are tab-separated. I'm not sure if this is only TJL or if this is generally true.
