### ISSUE TITLE
Need to accept .jpeg images

### ISSUE THREAD

**Issue by JayLucky** [Corridors-of-Time-Transcription/puzzlepieces#36]
https://github.com/Corridors-of-Time-Transcription/puzzlepieces/blob/0e9a0e3e4d65ddde707049b98f87fea5cd64d4c4/src/collector/views.py#L117

Update to include .jpeg as a valid extension.  Reference - https://www.reddit.com/r/raidsecrets/comments/eqmr1o/new_site_to_crowdsource_transcription_of/few52mp?utm_source=share&utm_medium=web2x

**Comment by afriestad** [comment]
This has been fixed with Pull Request #50.
